Repository mini-roostico/api-web, pull requests merged in 2025-02, with the labels that each got.

#25 Build/local package
  .github/workflows/build-check-deploy.yml
  api/.dockerignore
  api/Dockerfile
  api/package-lock.json
  api/package.json
  api/src/app.ts
  api/src/configs/server.configs.ts
  api/src/controllers/sources.ts
  api/src/controllers/users.ts
  api/src/routes/source.route.ts
  api/src/routes/user.route.ts
  api/tsconfig.json
  auth/Dockerfile
  auth/package-lock.json
  auth/package.json
  auth/tsconfig.json
  common/src/errors/errors.ts
  common/src/index.ts
  common/src/middleware/authentication.middleware.ts
  common/src/middleware/error.middleware.ts
  common/src/middleware/limiter.middleware.ts
  common/src/middleware/response.middleware.ts
  common/src/middleware/validation.middleware.ts
  common/src/models/jwt/jwt.ts
  common/src/models/users/users.ts
  common/src/utils/jwt/jwt.handler.ts
  common/src/utils/response/response.ts
  common/tsconfig.json
Labels: enhancement, bugfix

#24 feat: add auth app and configs
  api/package-lock.json
  api/src/app.ts
  auth/package-lock.json
  auth/package.json
  auth/src/app.ts
  auth/src/configs/express.config.ts
  auth/src/configs/mongoose.config.ts
  auth/src/configs/redis.config.ts
  auth/tsconfig.json
Labels: enhancement

#43 fix: updated all keys' env variables to new name
  api/src/configs/server.configs.ts
  auth/src/configs/express.config.ts
  common/src/utils/jwt/jwt.handler.ts
  docker-compose.yaml
Labels: bugfix

#46 refactor: added firstName to login return
  auth/src/controllers/auth.ts
Labels: enhancement

#48 test: provided user tests, fixed ac rules
  api/src/configs/accesscontrol.config.ts
  api/src/controllers/sources.ts
  api/src/controllers/users.ts
  api/src/routes/user.route.ts
  api/test/example.test.ts
  api/test/user.test.ts
Labels: enhancement

#49 docs: provided swagger docs for api and auth routes
  api/Dockerfile
  api/package-lock.json
  api/package.json
  api/src/configs/server.configs.ts
  api/src/doc/doc-gen.ts
  api/src/routes/source.route.ts
  api/src/routes/user.route.ts
  api/swagger.json
  auth/Dockerfile
  auth/package-lock.json
  auth/package.json
  auth/src/configs/express.config.ts
  auth/src/doc/doc-gen.ts
  auth/src/routes/auth.route.ts
  auth/swagger.json
  common/package-lock.json
  docker-compose.yaml
  startup.sh
Labels: documentation

#50 Test/api source
  api/src/controllers/sources.ts
  api/test/source.test.ts
  api/test/user.test.ts
  common/src/utils/local.db.ts
Labels: enhancement

#51 test: provided test for common
  api/package-lock.json
  auth/package-lock.json
  auth/src/configs/redis.config.ts
  common/babel.config.cjs
  common/jest.config.js
  common/package-lock.json
  common/package.json
  common/src/models/users/users.ts
  common/test/jest.setup.ts
  common/test/jwt.handler.test.ts
  common/test/jwt.test.ts
  common/test/sources.test.ts
  common/test/users.test.ts
  common/tsconfig.json
  package.json
Labels: enhancement

#55 feat: add repositories for users and sources
  api/src/controllers/sources.ts
  api/src/controllers/users.ts
  api/src/models/models.ts
  api/src/routes/source.route.ts
  api/src/routes/user.route.ts
  api/test/source.test.ts
  api/test/user.test.ts
  auth/src/controllers/auth.ts
  auth/src/models/models.ts
  auth/src/routes/auth.route.ts
  auth/test/auth.test.ts
  common/src/index.ts
  common/src/middleware/authentication.middleware.ts
  common/src/models/repository/sources.repository.ts
  common/src/models/repository/users.repository.ts
Labels: enhancement

#56 fix: removed dev dependencies from builds
  api/Dockerfile
  auth/Dockerfile
Labels: enhancement

#58 docs: add swagger.json in gitignore
  .gitignore
Labels: bugfix
